����� ������: 2024-10-08 12:07:52.086324
��� ������: TypeError
��������� ������: ('exceptions must derive from BaseException',)
������ traceback:
Traceback (most recent call last):
  File "C:\Users\kiril.KURILL\PycharmProjects\Monica\main.py", line 16, in <module>
    raise "��������"
TypeError: exceptions must derive from BaseException

--------------------------------------------------
Время ошибки: 2024-10-08 12:08:52.717257
Тип ошибки: TypeError
Аргументы ошибки: ('exceptions must derive from BaseException',)
Полный traceback:
Traceback (most recent call last):
  File "C:\Users\kiril.KURILL\PycharmProjects\Monica\main.py", line 16, in <module>
    raise "проверка"
TypeError: exceptions must derive from BaseException

--------------------------------------------------
Время ошибки: 2024-10-16 18:00:58.318996
Тип ошибки: Exception
Аргументы ошибки: ('Failed to create a model',)
Полный traceback:
Traceback (most recent call last):
  File "C:\Users\kiril.KURILL\PycharmProjects\Monica\main.py", line 46, in <module>
    voice_thread = VoiceThread()
                   ^^^^^^^^^^^^^
  File "C:\Users\kiril.KURILL\PycharmProjects\Monica\main.py", line 16, in __init__
    self.voice_controller = VoiceController()
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\kiril.KURILL\PycharmProjects\Monica\functional\voice_controller.py", line 11, in __init__
    self.model = Model("vosk-model-small-ru-0.22")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kiril.KURILL\AppData\Local\pypoetry\Cache\virtualenvs\monica-szJJKUHw-py3.12\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

--------------------------------------------------
